- name: Install and start Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Check if Nginx package is already installed
      command: rpm -q nginx
      register: nginx_check
      ignore_errors: yes

    - name: Skip Nginx installation if already installed
      debug:
        msg: "Nginx is already installed, skipping installation."
      when: nginx_check.rc == 0

    - name: Install Nginx package if not already installed
      yum:
        name: nginx
        state: present
      when: nginx_check.rc != 0

    - name: Ensure Nginx service is running
      service:
        name: nginx
        state: started
        enabled: yes
