- name: Install and start Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Check if Nginx package is installed
      yum:
        name: nginx
        state: present
      register: nginx_install_result

    - name: Display message if Nginx is already installed on this host
      debug:
        msg: "Nginx is already installed on {{ inventory_hostname }}."
      when: not nginx_install_result.changed

    - name: Install Nginx package if not already installed
      yum:
        name: nginx
        state: present
      when: nginx_install_result.changed

    - name: Check if Nginx service is running
      service_facts:

    - name: Display message if Nginx service is already running on this host
      debug:
        msg: "Nginx service is already running on {{ inventory_hostname }}."
      when: "'nginx' in ansible_facts.services and ansible_facts.services['nginx'].state == 'running'"

    - name: Ensure Nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      when: "'nginx' not in ansible_facts.services or ansible_facts.services['nginx'].state != 'running'"
