- name: Install and start Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Install Nginx package
      yum:
        name: nginx
        state: present
    - name: Ensure Nginx service is running
      service:
        name: nginx
        state: started
        enabled: yes
