- name: Install and start Nginx
  hosts: web_servers
  become: yes
  vars:
    already_installed: 0
    newly_installed: 0
    already_running: 0
    newly_started: 0
  tasks:
    - name: Check if Nginx package is installed
      yum:
        name: nginx
        state: present
      register: nginx_install_result

    - name: Increment already_installed if Nginx is already installed
      set_fact:
        already_installed: "{{ already_installed + 1 }}"
      when: not nginx_install_result.changed

    - name: Increment newly_installed if Nginx is newly installed
      set_fact:
        newly_installed: "{{ newly_installed + 1 }}"
      when: nginx_install_result.changed

    - name: Check if Nginx service is running
      service_facts:

    - name: Increment already_running if Nginx service is already running
      set_fact:
        already_running: "{{ already_running + 1 }}"
      when: "'nginx' in ansible_facts.services and ansible_facts.services['nginx'].state == 'running'"

    - name: Start and enable Nginx service if not running
      service:
        name: nginx
        state: started
        enabled: yes
      when: "'nginx' not in ansible_facts.services or ansible_facts.services['nginx'].state != 'running'"
      register: nginx_start_result

    - name: Increment newly_started if Nginx service was newly started
      set_fact:
        newly_started: "{{ newly_started + 1 }}"
      when: nginx_start_result.changed

    - name: Display summary of Nginx installation and running status
      debug:
        msg: |
          Summary:
          - Hosts with Nginx already installed: {{ already_installed }}
          - Hosts where Nginx was newly installed: {{ newly_installed }}
          - Hosts with Nginx already running: {{ already_running }}
          - Hosts where Nginx was newly started: {{ newly_started }}
